<a href="https://www.kaggle.com/code/iqmansingh/tensorflow-2-0-basics-notebook?scriptVersionId=134155664" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# **TensorFlow 2.0 Notebook**

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
caused by: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so: undefined symbol: _ZN3tsl6StatusC1EN10tensorflow5error4CodeESt17basic_string_viewIcSt11char_traitsIcEENS_14SourceLocationE']
  warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: libtensorflow_io.so, from paths: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io.so']
caused by: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io.so: undefined symbol: _ZTVN10tenso

In [2]:
tf.__version__

'2.12.0'

# Defining a constant 

In [3]:
tensor = tf.constant([[23,4],[32,51]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [4]:
tensor.shape

TensorShape([2, 2])

In [5]:
tensor.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [6]:
arr = np.array([[20,4],[21,51]])
np_tensor = tf.constant(arr)
np_tensor

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[20,  4],
       [21, 51]])>

# Variables

In [7]:
variable = tf.Variable([[1.0,2.0],[3.0,4.0]])
variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [8]:
variable.shape

TensorShape([2, 2])

In [9]:
variable.numpy()

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [10]:
variable[0,1].assign(8)
variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 8.],
       [3., 4.]], dtype=float32)>

# Operations with Tensors

In [11]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [12]:
tensor * 3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 69,  12],
       [ 96, 153]], dtype=int32)>

In [13]:
np.square(tensor)

array([[ 529,   16],
       [1024, 2601]], dtype=int32)

In [14]:
tensor/2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[11.5,  2. ],
       [16. , 25.5]])>

In [15]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [16]:
tensor = tensor/2
tensor

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[11.5,  2. ],
       [16. , 25.5]])>

In [17]:
np.dot(tensor,tensor) # Dot product between 2 tensors

array([[164.25,  74.  ],
       [592.  , 682.25]])

# Strings

In [18]:
tf_str = tf.constant("Iqman")
tf_str

<tf.Tensor: shape=(), dtype=string, numpy=b'Iqman'>

In [19]:
tf.strings.length(tf_str)

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [20]:
tf.strings.length(tf_str).numpy()

5

In [21]:
tf.strings.unicode_decode(tf_str,"UTF8")

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 73, 113, 109,  97, 110], dtype=int32)>

# Array of String

In [22]:
tf_arr = tf.constant(["Iqman","Singh","Bhatia"])

In [23]:
for i in tf_arr:
    print(i.numpy(),"; Length is:",tf.strings.length(i).numpy())

b'Iqman' ; Length is: 5
b'Singh' ; Length is: 5
b'Bhatia' ; Length is: 6
