# **TensorFlow 2.0 Notebook**

In [24]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [25]:
tf.__version__

'2.12.0'

# Defining a constant 

In [26]:
tensor = tf.constant([[23,4],[32,51]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [27]:
tensor.shape

TensorShape([2, 2])

In [28]:
tensor.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [29]:
arr = np.array([[20,4],[21,51]])
np_tensor = tf.constant(arr)
np_tensor

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[20,  4],
       [21, 51]])>

# Variables

In [30]:
variable = tf.Variable([[1.0,2.0],[3.0,4.0]])
variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [31]:
variable.shape

TensorShape([2, 2])

In [32]:
variable.numpy()

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [33]:
variable[0,1].assign(8)
variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 8.],
       [3., 4.]], dtype=float32)>

# Operations with Tensors

In [34]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [35]:
tensor * 3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 69,  12],
       [ 96, 153]], dtype=int32)>

In [36]:
np.square(tensor)

array([[ 529,   16],
       [1024, 2601]], dtype=int32)

In [37]:
tensor/2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[11.5,  2. ],
       [16. , 25.5]])>

In [38]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [39]:
tensor = tensor/2
tensor

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[11.5,  2. ],
       [16. , 25.5]])>

In [40]:
np.dot(tensor,tensor) # Dot product between 2 tensors

array([[164.25,  74.  ],
       [592.  , 682.25]])

# Strings

In [44]:
tf_str = tf.constant("Iqman")
tf_str

<tf.Tensor: shape=(), dtype=string, numpy=b'Iqman'>

In [45]:
tf.strings.length(tf_str)

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [47]:
tf.strings.length(tf_str).numpy()

5

In [48]:
tf.strings.unicode_decode(tf_str,"UTF8")

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 73, 113, 109,  97, 110], dtype=int32)>

# Array of String

In [56]:
tf_arr = tf.constant(["Iqman","Singh","Bhatia"])

In [61]:
for i in tf_arr:
    print(i.numpy(),"; Length is:",tf.strings.length(i).numpy())

b'Iqman' ; Length is: 5
b'Singh' ; Length is: 5
b'Bhatia' ; Length is: 6
